<?php
  # Config
  $author = "Jhon Doe";
  $author_webpage = "#";
  $title = "Lorem Ipsum";
  $description = "";
  $date = "14-08-2020";
  $prestory = "All the dates in this example are in DD/MM/YYYY";
  $story = "
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pretium augue et neque faucibus, ut faucibus enim pellentesque. Quisque eu metus eu augue vestibulum posuere. Maecenas pharetra diam vel ex dictum vulputate. Etiam viverra fringilla arcu eu ullamcorper. Maecenas vestibulum sit amet arcu vitae faucibus. Sed ipsum ligula, tempor et lorem eget, volutpat rhoncus quam. Pellentesque nec vehicula ligula, quis porttitor leo. Praesent purus libero, ultricies ut porttitor ut, posuere at nibh. Proin tincidunt enim ac magna dapibus aliquam. Aenean sit amet iaculis leo.
    <br></br>
    Donec non quam id odio aliquam consequat sit amet in libero. In purus est, feugiat non nunc sed, luctus tincidunt elit. Vivamus tortor urna, lobortis malesuada egestas eu, aliquam tempus nibh. Maecenas iaculis orci orci, sed facilisis odio sodales in. Quisque vitae urna at justo elementum pulvinar ut et nisi. Donec non est a turpis lobortis volutpat. Mauris nibh metus, luctus ullamcorper blandit non, porta quis libero. Vestibulum vitae nisi scelerisque, fermentum arcu eu, rhoncus erat. Quisque eros massa, mollis in nunc non, bibendum maximus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc ligula magna, dapibus sit amet venenatis id, lacinia sed quam. Curabitur condimentum, neque et tincidunt tincidunt, magna ante consectetur dolor, sed molestie odio purus sit amet tellus. Sed porttitor aliquam odio, nec interdum elit convallis ut. Mauris ex leo, sagittis in lacus in, tincidunt pellentesque diam. Mauris commodo fringilla elit, in pharetra lacus mattis nec. Nam viverra pretium consectetur.
    <br></br>
    Vivamus fringilla laoreet facilisis. Vestibulum varius pulvinar nunc, vitae rhoncus nulla cursus et. Aenean iaculis dui et tincidunt blandit. Sed hendrerit velit nisl, eu placerat lectus commodo nec. Nunc aliquam iaculis eros, non placerat leo faucibus eget. Fusce non sem id risus eleifend viverra. Nullam elementum ex urna, sed elementum nisi aliquam sed.
    <br></br>
    Quisque nec ante viverra, elementum nunc eu, volutpat felis. Proin feugiat molestie sapien, vel laoreet dolor mattis ac. Nullam tristique nunc turpis, et iaculis purus convallis quis. Proin vitae orci ac arcu ornare consectetur. Aenean pulvinar est vitae sem euismod dapibus. Vestibulum tincidunt fringilla magna sed faucibus. Cras sed rhoncus enim. Aliquam aliquam et libero id iaculis. Fusce ullamcorper urna non posuere rutrum. Duis vel leo ut quam pellentesque faucibus eu id quam. Suspendisse varius enim eget nisl luctus sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent a ante laoreet arcu lobortis maximus ac eget lectus. Cras at placerat massa. Nunc ac tristique lectus, in fermentum metus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
    <br></br>
    Integer convallis, nunc ut pharetra pharetra, massa ligula tempus lorem, id imperdiet mi turpis nec sem. Sed semper libero ut diam auctor, convallis finibus libero varius. In ut neque non urna pulvinar vulputate et non augue. Integer rhoncus sapien eget rutrum tempus. Sed massa turpis, bibendum sed condimentum euismod, hendrerit fermentum libero. Quisque eu lorem erat. Praesent et metus odio. Praesent nisl lacus, ornare eget molestie consequat, tincidunt eu ex. Donec posuere vestibulum maximus. Donec ut mauris sed neque feugiat posuere in vitae augue. Curabitur et rutrum enim. In non viverra purus.
    <br></br>
    Nullam at vestibulum arcu, at vehicula risus. Morbi velit turpis, commodo a sapien eget, cursus ultrices tellus. Etiam mi purus, aliquet nec aliquam et, ornare vitae erat. Maecenas at metus lectus. Vivamus nec gravida dolor, quis porta lacus. Suspendisse sit amet leo nisl. Pellentesque commodo, mauris ultrices aliquet iaculis, nunc urna ultricies quam, nec varius quam sapien sed turpis. In ac iaculis risus. Praesent accumsan orci vitae urna fermentum semper.
    <br></br>
    Aliquam sed molestie arcu, vitae tristique ex. Mauris a felis non nisi tempor rutrum eu nec massa. Curabitur id purus ac ligula dapibus pharetra vel vel metus. Duis augue felis, sollicitudin quis consectetur a, laoreet quis neque. Mauris iaculis vehicula orci et vestibulum. Vivamus dolor sapien, bibendum sed aliquet vitae, laoreet id enim. Curabitur ac rutrum sem. Vivamus iaculis quam in massa commodo, ut malesuada mauris cursus. Nulla viverra, odio ac interdum scelerisque, risus dui sodales magna, vitae tempus nibh nulla sed tortor.
    <br></br>
    Quisque laoreet consequat ornare. Integer nec nulla vulputate, fringilla turpis ac, aliquam lacus. Nam pretium ac felis nec feugiat. Donec lacinia, lacus ut euismod interdum, ipsum orci tincidunt eros, non ultrices ex nisi ut eros. Aenean venenatis hendrerit sapien, quis imperdiet nibh congue ac. Nam suscipit enim a orci vehicula malesuada. Proin sit amet lorem diam. Suspendisse ac sagittis est. Aenean ornare ex est, non feugiat quam elementum et. Praesent id mi a nibh ullamcorper condimentum eget vel nunc. Praesent gravida semper pharetra. Pellentesque posuere mauris sed lorem congue euismod. Vivamus egestas sapien lorem, sed tempor quam suscipit eget.
    <br></br>
    Nam cursus quam nisi. Praesent nunc mi, elementum commodo dignissim sed, pretium vel nunc. Vestibulum rutrum risus in ipsum tempus, vel varius purus tristique. Curabitur et nibh semper, fermentum metus sit amet, imperdiet nunc. Aliquam quis hendrerit ante, eu hendrerit augue. Nullam vehicula commodo dignissim. Fusce maximus pretium volutpat. Proin in eleifend neque. Morbi vel convallis eros. Sed sit amet rutrum risus. Sed risus lacus, facilisis in odio ut, congue bibendum lacus. Maecenas vel pharetra risus, a tincidunt metus.
    <br></br>
    Vestibulum sit amet efficitur elit. Vivamus eu ullamcorper est. Nullam ornare, velit at sagittis dictum, urna dolor varius enim, sodales facilisis est massa et metus. Maecenas id odio facilisis, vulputate risus fringilla, rhoncus mi. Nam dignissim molestie pretium. Maecenas facilisis tristique dictum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam rutrum efficitur urna, a lobortis sem venenatis sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur volutpat purus enim, sit amet blandit nunc malesuada sed. Mauris molestie quam tortor, id convallis lectus pulvinar nec. Praesent auctor urna eu ipsum hendrerit finibus. Ut nec est dui. Maecenas blandit nulla et fringilla viverra. Donec eu rutrum ex, a facilisis ligula. Aenean luctus ultricies ornare.
    <br></br>
    Quisque a aliquam tortor, a volutpat velit. Sed ut arcu magna. Pellentesque posuere, tellus eu egestas efficitur, lectus enim efficitur nunc, in varius justo nisl ac nulla. Suspendisse nibh neque, cursus id tincidunt sit amet, feugiat id lectus. Nam.
  ";
  # IMPORTANT!!!!!
  include "posts.php";
?>
